### ISSUE TITLE
npm install throws CERT_UNTRUSTED

### ISSUE THREAD

**Issue by hupasuperstrip** [actions/npm#16] opened 2018-12-20 18:31 UTC
the call shows the following
npm http GET https://registry.npmjs.org/ronn
npm http GET https://registry.npmjs.org/tap
npm http GET https://registry.npmjs.org/ronn
npm http GET https://registry.npmjs.org/tap
npm http GET https://registry.npmjs.org/ronn
npm http GET https://registry.npmjs.org/tap
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR!     at flow (_stream_readable.js:611:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:643:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-696.18.7.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/lib/node_modules/npm
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6

**Comment by mcolyer** [comment] 2019-01-02 19:38
Closing this as a duplicate of #15.

**Closed by mcolyer** 2019-01-02 19:38 UTC
